name: Package APK

on:
  repository_dispatch:
    types: [new-so]
  workflow_dispatch:
    inputs:
      run_id:
        required: true
        description: "Run ID do build da .so"
      artifact:
        required: false
        default: "libquanneggaes4d-android-arm64-v8a"

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get run_id and artifact name
        run: |
          RUN_ID=${{ github.event.client_payload.run_id || github.event.inputs.run_id }}
          ARTIFACT=${{ github.event.client_payload.artifact || github.event.inputs.artifact || 'libquanneggaes4d-android-arm64-v8a' }}
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "ARTIFACT=$ARTIFACT" >> $GITHUB_ENV

      - name: Download libquanneggaes4d.so
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACT }}
          github-token: ${{ secrets.GH_TOKEN }}
          repository: denocraftplayerg-max/Mbglues
          run-id: ${{ env.RUN_ID }}

      - name: Inject .so
        run: |
          mkdir -p QUANNEGGAES4D/src/main/jniLibs/arm64-v8a
          mv libquanneggaes4d.so QUANNEGGAES4D/src/main/jniLibs/arm64-v8a/

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install NDK 27.3.13750724
        run: |
          echo "y" | sdkmanager "ndk;27.3.13750724"
          echo "ANDROID_NDK_HOME=$ANDROID_HOME/ndk/27.3.13750724" >> $GITHUB_ENV

      - name: Build APK
        env:
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        run: |
          chmod +x gradlew
          ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Quanneggaes4d-plugin-release
          path: app/build/outputs/apk/release/*.apk
          retention-days: 30
